use_frameworks!

target 'AzureCore_Example' do
  pod 'AzureCore', :path => '../'

  target 'AzureCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
