- color: "131aa3"
  description: ""
  name: 0 - Backlog
- color: "e99695"
  description: ""
  name: AAD
- color: "e99695"
  description: ""
  name: ACS
- color: "e99695"
  description: ""
  name: AKS
- color: "e99695"
  description: ""
  name: API Management
- color: "ffdd00"
  description: This PR contains an addition or change to the API signature and must
    be reviewed by an architect.
  name: APIChange
- color: "e99695"
  description: ""
  name: ARM
- color: "e99695"
  description: ""
  name: ARM - Core
- color: "e99695"
  description: ""
  name: ARM - Managed Applications
- color: "e99695"
  description: ""
  name: ARM - RBAC
- color: "e99695"
  description: ""
  name: ARM - Service Catalog
- color: "e99695"
  description: ""
  name: ARM - Tags
- color: "e99695"
  description: ""
  name: ARM - Templates
- color: "d8f74c"
  description: ""
  name: ARM-Core Review
- color: "f7ec25"
  description: ""
  name: ARM-Core Triaged
- color: "e99695"
  description: Azure Redhat OpenShift
  name: ARO
- color: "e99695"
  description: ""
  name: AVS
- color: "e99695"
  description: ""
  name: Advisor
- color: "e99695"
  description: ""
  name: Alerts Management
- color: "e99695"
  description: ""
  name: Analysis Services
- color: "e99695"
  description: Azure.ApplicationModel.Configuration
  name: App Configuration
- color: "e99695"
  description: ""
  name: App Services
- color: "e99695"
  description: App Authentication, MSI
  name: AppAuthentication
- color: "33bb00"
  description: This API addition or change has been reviewed and approved by a language
    architect.
  name: ArchApproved
- color: "e99695"
  description: ""
  name: Attestation
- color: "e99695"
  description: ""
  name: Authentication
- color: "e99695"
  description: ""
  name: Authorization
- color: "e99695"
  description: ""
  name: AutoRest Runtime
- color: "e99695"
  description: ""
  name: Automation
- color: "5fe2d1"
  description: Issues assigned to the Azure Net SDK team
  name: Az Net SDK Team
- color: "e99695"
  description: ""
  name: Azure Arc enabled servers
- color: "e99695"
  description: ""
  name: Azure Data Explorer
- color: "e99695"
  description: ""
  name: Azure Stack
- color: "e99695"
  description: ""
  name: Azure.Core
- color: "e99695"
  description: ""
  name: Azure.Identity
- color: "e99695"
  description: ""
  name: Azure.Spring - Cosmos
- color: "e99695"
  description: Issues related to the Azure.Template project that can be used as a
    starting point for our libraries.
  name: Azure.Template
- color: "e99695"
  description: ""
  name: Batch
- color: "e99695"
  description: ""
  name: BatchAI
- color: "e99695"
  description: ""
  name: Billing
- color: "e99695"
  description: ""
  name: Blueprint
- color: "e99695"
  description: ""
  name: Bot Service
- color: "ffeb77"
  description: This issue is owned by the Engineering System team.
  name: Central-EngSys
- color: "a9c6fc"
  description: ""
  name: Changes Requested
- color: "ffeb77"
  description: This issue points to a problem in the data-plane of the library.
  name: Client
- color: "e99695"
  description: ""
  name: Cloud Shell
- color: "e99695"
  description: Issues that relate to code generation
  name: CodeGen
- color: "e99695"
  description: ""
  name: Cognitive - Anomaly Detector
- color: "e99695"
  description: ""
  name: Cognitive - Bing
- color: "e99695"
  description: ""
  name: Cognitive - Computer Vision
- color: "e99695"
  description: ""
  name: Cognitive - Content Moderator
- color: "e99695"
  description: ""
  name: Cognitive - Custom Vision
- color: "e99695"
  description: ""
  name: Cognitive - Face
- color: "e99695"
  description: ""
  name: Cognitive - Form Recognizer
- color: "e99695"
  description: ""
  name: Cognitive - Immersive Reader
- color: "e99695"
  description: ""
  name: Cognitive - Ink Recognizer
- color: "e99695"
  description: ""
  name: Cognitive - LUIS
- color: "e99695"
  description: ""
  name: Cognitive - Metrics Advisor
- color: "e99695"
  description: ""
  name: Cognitive - Mgmt
- color: "e99695"
  description: ""
  name: Cognitive - Personalizer
- color: "e99695"
  description: ""
  name: Cognitive - QnA Maker
- color: "e99695"
  description: ""
  name: Cognitive - Speech
- color: "e99695"
  description: ""
  name: Cognitive - Text Analytics
- color: "e99695"
  description: ""
  name: Cognitive - Translator
- color: "e99695"
  description: ""
  name: Cognitive - Vision
- color: "e99695"
  description: ""
  name: Cognitive Services
- color: "e99695"
  description: ""
  name: Commerce
- color: "e99695"
  description: ""
  name: Communication
- color: "1aa874"
  description: Community member is working on the issue
  name: Community Contribution
- color: "e99695"
  description: ""
  name: Compute
- color: "e99695"
  description: ""
  name: Compute - Extensions
- color: "e99695"
  description: ""
  name: Compute - Images
- color: "e99695"
  description: ""
  name: Compute - Managed Disks
- color: "e99695"
  description: ""
  name: Compute - RDFE
- color: "e99695"
  description: ""
  name: Compute - VM
- color: "e99695"
  description: ""
  name: Compute - VMSS
- color: "e99695"
  description: ""
  name: Connected Kubernetes
- color: "e99695"
  description: ""
  name: Consumption
- color: "e99695"
  description: ""
  name: Container Instances
- color: "e99695"
  description: ""
  name: Container Registry
- color: "e99695"
  description: ""
  name: Container Service
- color: "e99695"
  description: ""
  name: Cosmos
- color: "e99695"
  description: ""
  name: Cost Management
- color: "e99695"
  description: ""
  name: Custom Providers
- color: "e99695"
  description: ""
  name: Customer Insights
- color: "e99695"
  description: ""
  name: CycleCloud
- color: "e99695"
  description: ""
  name: Data Bricks
- color: "e99695"
  description: ""
  name: Data Catalog
- color: "e99695"
  description: ""
  name: Data Factory
- color: "e99695"
  description: ""
  name: Data Lake
- color: "e99695"
  description: ""
  name: Data Lake Analytics
- color: "e99695"
  description: ""
  name: Data Lake Storage Gen1
- color: "e99695"
  description: ""
  name: Data Lake Storage Gen2
- color: "e99695"
  description: ""
  name: Data Lake Store
- color: "e99695"
  description: ""
  name: Data Migration
- color: "e99695"
  description: ""
  name: Data Share
- color: "e99695"
  description: ""
  name: DataBox
- color: "e99695"
  description: ""
  name: DataBox Edge
- color: "e99695"
  description: ""
  name: Dev Spaces
- color: "e99695"
  description: ""
  name: DevOps
- color: "e99695"
  description: ""
  name: Devtestlab
- color: "e99695"
  description: ""
  name: Digital Twins
- color: "e99695"
  description: ""
  name: DigitalTwins
- color: "b60205"
  description: ""
  name: Do Not Merge
- color: "e99695"
  description: ""
  name: Docs
- color: "e99695"
  description: ""
  name: Docs-Hackathon
- color: "e99695"
  description: This issue is impacting the engineering system.
  name: EngSys
- color: "3E4B9E"
  description: ""
  name: Epic
- color: "e99695"
  description: ""
  name: Event Grid
- color: "e99695"
  description: ""
  name: Event Hubs
- color: "e99695"
  description: ASP.NET Core extensions
  name: Extensions
- color: "e99695"
  description: ""
  name: Functions
- color: "e99695"
  description: ""
  name: Graph
- color: "e99695"
  description: ""
  name: Graph.Microsoft
- color: "e99695"
  description: ""
  name: Graph.Windows
- color: "e99695"
  description: ""
  name: Guest Configuration
- color: "e99695"
  description: ""
  name: HDInsight
- color: "e99695"
  description: ""
  name: HPC Cache
- color: "e99695"
  description: ""
  name: Import Export
- color: "e99695"
  description: ""
  name: Insights
- color: "e99695"
  description: ""
  name: Intune
- color: "1d76db"
  description: ""
  name: Investigate
- color: "3ce08b"
  description: Pull requests that need to be reviewed by the IoT Managed SDK team
  name: IoT Managed SDK
- color: "e99695"
  description: ""
  name: IoT/CLI
- color: "e99695"
  description: ""
  name: Iot
- color: "e99695"
  description: ""
  name: KeyVault
- color: "e99695"
  description: ""
  name: Kubernetes Configuration
- color: "e99695"
  description: ""
  name: Kusto
- color: "e99695"
  description: ""
  name: LOUIS
- color: "e99695"
  description: ""
  name: Lab Services
- color: "e99695"
  description: ""
  name: Logic App
- color: "5df772"
  description: Storage "Milestone Quality" investments.
  name: MQ-Storage
- color: "e99695"
  description: ""
  name: Machine Learning
- color: "e99695"
  description: ""
  name: Machine Learning Compute
- color: "e99695"
  description: ""
  name: Machine Learning Experimentation
- color: "e99695"
  description: ""
  name: Managed Identity
- color: "e99695"
  description: ""
  name: ManagedServices
- color: "e99695"
  description: ""
  name: MariaDB
- color: "e99695"
  description: ""
  name: Marketplace Ordering
- color: "e99695"
  description: ""
  name: Media Services
- color: "b60205"
  description: ""
  name: Merge Conflicts
- color: "ffeb77"
  description: This issue points to a problem in the management-plane of the library.
  name: Mgmt
- color: "ffeb77"
  description: Engineering System (Management Plane Specific)
  name: Mgmt-EngSys
- color: "e99695"
  description: ""
  name: Migrate
- color: "f27941"
  description: ""
  name: Missing Spec PR link
- color: "e99695"
  description: ""
  name: Mobile Engagement
- color: "e99695"
  description: Monitor, Operational Insights
  name: Monitor
- color: "e99695"
  description: ""
  name: Monitor - ActionGroups
- color: "e99695"
  description: ""
  name: Monitor - ActivityLogs
- color: "e99695"
  description: ""
  name: Monitor - Alerts
- color: "e99695"
  description: ""
  name: Monitor - ApplicationInsights
- color: "e99695"
  description: ""
  name: Monitor - Autoscale
- color: "e99695"
  description: ""
  name: Monitor - Diagnostic Settings
- color: "e99695"
  description: ""
  name: Monitor - Exporter
- color: "e99695"
  description: ""
  name: Monitor - LogAnalytics
- color: "e99695"
  description: ""
  name: Monitor - Metrics
- color: "e99695"
  description: ""
  name: Monitor - Operational Insights
- color: "e99695"
  description: ""
  name: MySQL
- color: "e99695"
  description: ""
  name: Network
- color: "e99695"
  description: ""
  name: Network - Application Gateway
- color: "e99695"
  description: ""
  name: Network - Bastion
- color: "e99695"
  description: ""
  name: Network - CDN
- color: "e99695"
  description: ""
  name: Network - DDoS Protection
- color: "e99695"
  description: ""
  name: Network - DNS
- color: "e99695"
  description: ""
  name: Network - ExpressRoute
- color: "e99695"
  description: ""
  name: Network - Firewall
- color: "e99695"
  description: 'Service: Azure Front Door'
  name: Network - Front Door
- color: "e99695"
  description: ""
  name: Network - Load Balancer
- color: "e99695"
  description: ""
  name: Network - Network Virtual Appliance
- color: "e99695"
  description: ""
  name: Network - Network Watcher
- color: "e99695"
  description: ""
  name: Network - Private Link
- color: "e99695"
  description: ""
  name: Network - Traffic Manager
- color: "e99695"
  description: ""
  name: Network - VPN Gateway
- color: "e99695"
  description: ""
  name: Network - Virtual Network
- color: "e99695"
  description: ""
  name: Network - Virtual Network NAT
- color: "e99695"
  description: ""
  name: Network - Virtual WAN
- color: "e99695"
  description: ""
  name: Notification Hub
- color: "e99695"
  description: ""
  name: Operations Management
- color: "e99695"
  description: ""
  name: Peering
- color: "22AA22"
  description: ""
  name: Performance
- color: "c5def5"
  description: ""
  name: Planning
- color: "e99695"
  description: ""
  name: Policy
- color: "e99695"
  description: ""
  name: Policy Insights
- color: "e99695"
  description: ""
  name: PostgreSQL
- color: "e99695"
  description: ""
  name: PowerBI
- color: "e99695"
  description: ""
  name: Recovery Services Backup
- color: "e99695"
  description: ""
  name: Recovery Services Site-Recovery
- color: "e99695"
  description: ""
  name: Redis Cache
- color: "e99695"
  description: ""
  name: Relay
- color: "e99695"
  description: ""
  name: Reservations
- color: "e99695"
  description: ""
  name: Resource Authorization
- color: "e99695"
  description: ""
  name: Resource Graph
- color: "e99695"
  description: ""
  name: Resource Health
- color: "e99695"
  description: ""
  name: SQL
- color: "e99695"
  description: ""
  name: SQL - Backup & Restore
- color: "e99695"
  description: ""
  name: SQL - Data Security
- color: "e99695"
  description: ""
  name: SQL - Elastic Jobs
- color: "e99695"
  description: ""
  name: SQL - Managed Instance
- color: "e99695"
  description: ""
  name: SQL - Replication & Failover
- color: "e99695"
  description: ""
  name: SQL - VM
- color: "c7f9fc"
  description: ""
  name: STG71
- color: "e2e532"
  description: ""
  name: SToS
- color: "e99695"
  description: ""
  name: Scheduler
- color: "e99695"
  description: ""
  name: Schema Registry
- color: "e99695"
  description: ""
  name: Search
- color: "e99695"
  description: ""
  name: Security
- color: "e99695"
  description: ""
  name: SecurityInsights
- color: "e99695"
  description: ""
  name: Server Management
- color: "ffeb77"
  description: This issue points to a problem in the service.
  name: Service
- color: "10066b"
  description: This issue is responsible by Azure service team.
  name: Service Attention
- color: "e99695"
  description: ""
  name: Service Bus
- color: "e99695"
  description: ""
  name: Service Fabric
- color: "e99695"
  description: ""
  name: Service Map
- color: "e99695"
  description: ""
  name: SignalR
- color: "fef2c0"
  description: Anything older than 1 year without activity.
  name: Stale
- color: "e99695"
  description: Storage Service (Queues, Blobs, Files)
  name: Storage
- color: "e99695"
  description: ""
  name: StorageTable
- color: "e99695"
  description: ""
  name: Storsimple
- color: "e99695"
  description: ""
  name: Stream Analytics
- color: "abfcc5"
  description: ""
  name: Stress
- color: "e99695"
  description: ""
  name: Subscription
- color: "e99695"
  description: ""
  name: Support
- color: "e99695"
  description: ""
  name: Synapse
- color: "e99695"
  description: ""
  name: Tables
- color: "d93f0b"
  description: ""
  name: Test Debt
- color: "e99695"
  description: ""
  name: TimeseriesInsights
- color: "96d8f2"
  description: ""
  name: Track 1
- color: "96d8f2"
  description: Track 2 Azure SDK
  name: Track 2
- color: "e99695"
  description: Work items that track the work to build training materials for building
    Client libraries
  name: Training
- color: "e99695"
  description: ""
  name: Visual Studio
- color: "e99695"
  description: ""
  name: Web Apps
- color: "e99695"
  description: ""
  name: Websites
- color: "2ea44f"
  description: Apply to PR's that we want to auto-merge when green
  name: auto-merge
- color: "bea6ea"
  description: This request requires a major version increase before being merged
    due to breaking changes.
  name: awaiting-next-major
- color: "d73a49"
  description: Blocks release
  name: blocking-release
- color: "ffe5bc"
  description: ""
  name: breaking-change
- color: "eaa875"
  description: This issue requires a change to an existing behavior in the product
    in order to be resolved.
  name: bug
- color: "3800e0"
  description: Issues that are reported by GitHub users external to the Azure organization.
  name: customer-reported
- color: "4cdb56"
  description: An area of design currently under discussion and open to team and community
    feedback.
  name: design-discussion
- color: "eaa875"
  description: This issue requires a new behavior in the product in order be resolved.
  name: feature-request
- color: "aaf5af"
  description: This issue tracks work that may be a good starting point for a first-time
    contributor
  name: good first issue
- color: "64c170"
  description: This issue is tracking work for which community contributions would
    be welcomed and appreciated
  name: help wanted
- color: "058e2c"
  description: ""
  name: manual-test-pass
- color: "6cb6d8"
  description: ""
  name: multi-api-sdk
- color: "f72598"
  description: More information is needed from author to address the issue.
  name: needs-author-feedback
- color: "fbcfff"
  description: ""
  name: needs-review
- color: "fd8c00"
  description: ""
  name: needs-revision
- color: "3BA0F8"
  description: This issue needs attention from Azure service team or SDK team
  name: needs-team-attention
- color: "ededed"
  description: This issue needs the team to triage.
  name: needs-team-triage
- color: "ededed"
  description: This is a new issue that needs to be triaged to the appropriate team.
  name: needs-triage
- color: "bbbbbb"
  description: There has been no recent activity on this issue.
  name: no-recent-activity
- color: "b8cbf2"
  description: ""
  name: not blocking
- color: "eaa875"
  description: The issue doesn't require a change to the product in order to be resolved.
    Most issues start as that
  name: question
- color: "d73a49"
  description: Bugs that require a hotfix release
  name: servicing
- color: "ff0000"
  description: ""
  name: spec-not-merged
- color: "5cc946"
  description: ""
  name: tenet-reliability
- color: "249bbf"
  description: ""
  name: test-enhancement
- color: "c0eaf9"
  description: ""
  name: test-manual-pass
- color: "D20E0E"
  description: Issue that causes tests to be unreliable
  name: test-reliability
- color: "ddd716"
  description: ""
  name: test-sovereign-cloud
- color: "e99695"
  description: ""
  name: vFXT

