
# --------------------------------------------------------------------------
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# The MIT License (MIT)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the ""Software""), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#
# --------------------------------------------------------------------------

platform :ios, '13.0'

# Determine linkage type
if ENV['PODS_LINKAGE']&.downcase == 'static'
  puts 'Using Static Libraries'
elsif ENV['PODS_LINKAGE']&.downcase == 'staticframeworks'
  puts 'Using Static Frameworks'
  use_frameworks! :linkage => :static
else
  puts 'Using Frameworks'
  use_frameworks!
end

# determine if running on CI or not and populate local directory
is_ci = ENV.key?('IS_CI')
local_path = ENV['PODSPEC_DIR']
branch = (ENV['PODSPEC_BRANCH'] || 'main')

target 'AzureSDKSmokeTest' do
  if is_ci
    # install podspecs locally from source branch/PR
    pod 'AzureCore', :podspec => "#{local_path}/sdk/core/AzureCore/AzureCore.podspec.json"
#    pod 'AzureCommunicationCommon', :podspec => "#{local_path}/sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json"
#    pod 'AzureCommunicationChat', :podspec => "#{local_path}/sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json"
#    pod 'AzureCommunicationCalling', :podspec => "#{local_path}/sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json"
  else
    # manual run targets AzureSDK branch
    pod 'AzureCore', :podspec => "https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/#{branch}/sdk/core/AzureCore/AzureCore.podspec.json"
#    pod 'AzureCommunicationCommon', :podspec => "https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/#{branch}/sdk/communication/AzureCommunicationCommon/AzureCommunicationCommon.podspec.json"
#    pod 'AzureCommunicationChat', :podspec => "https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/#{branch}/sdk/communication/AzureCommunicationChat/AzureCommunicationChat.podspec.json"
#    pod 'AzureCommunicationCalling', :podspec => "https://raw.githubusercontent.com/Azure/azure-sdk-for-ios/#{branch}/sdk/communication/AzureCommunicationCalling/AzureCommunicationCalling.podspec.json"
  end
end

# disable bitcode due to Chat and Trouter
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end
