# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/template/
    - sdk/eng/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/template/
    - sdk/eng/

resources:
  repositories:
  - repository: SwiftPM-AzureTemplate
    type: github
    name: Azure/SwiftPM-AzureTemplate
    endpoint: Azure

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: template
    Artifacts:
    - name: AzureTemplate
    SourceRepositoriesToScan:
      - repository: SwiftPM-AzureTemplate