// --------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// --------------------------------------------------------------------------

import AzureCore
import Foundation
// swiftlint:disable superfluous_disable_command
// swiftlint:disable identifier_name
// swiftlint:disable line_length

/// User-configurable options for the `AzureCommunicationChatClient`.
public struct AzureCommunicationChatClientOptions: ClientOptions {
    /// The API version of the  to invoke.
    public let apiVersion: String
    /// The `ClientLogger` to be used by this `AzureCommunicationChatClient`.
    public let logger: ClientLogger
    /// Options for configuring telemetry sent by this `AzureCommunicationChatClient`.
    public let telemetryOptions: TelemetryOptions
    /// Global transport options
    public let transportOptions: TransportOptions
    /// The default dispatch queue on which to call all completion handler. Defaults to `DispatchQueue.main`.
    public let dispatchQueue: DispatchQueue?
    /// An array of `PipelineStage` policies to use in lieu of the default ones.
    public let pipeline: [PipelineStage]?
    /// An `HTTPTransportStage` policy to use in lieu of the default.
    public let transport: HTTPTransportStage?


    /// Initialize a `AzureCommunicationChatClientOptions` structure.
    /// - Parameters:
    ///   - apiVersion: The API version of the  to invoke.
    ///   - logger: The `ClientLogger` to be used by this `AzureCommunicationChatClient`.
    ///   - telemetryOptions: Options for configuring telemetry sent by this `AzureCommunicationChatClient`.
    ///   - cancellationToken: A token used to make a best-effort attempt at canceling a request.
    ///   - dispatchQueue: The default dispatch queue on which to call all completion handler. Defaults to `DispatchQueue.main`.
    ///   - pipeline: An array of `PipelineStage` policies to use in lieu of the default ones.
    ///   - transport: An `HTTPTransportStage` policy to use in lieu of the default.
    public init(
        apiVersion: AzureCommunicationChatClient.ApiVersion = .latest,
        logger: ClientLogger = ClientLoggers.default(tag: "AzureCommunicationChatClientClient"),
        telemetryOptions: TelemetryOptions = TelemetryOptions(),
        transportOptions: TransportOptions? = nil,
        dispatchQueue: DispatchQueue? = nil,
        pipeline: [PipelineStage]? = nil,
        transport: HTTPTransportStage? = nil
    ) {
        self.apiVersion = apiVersion.rawValue
        self.logger = logger
        self.telemetryOptions = telemetryOptions
        self.transportOptions = transportOptions ?? TransportOptions()
        self.dispatchQueue = dispatchQueue
        self.pipeline = pipeline
        self.transport = transport
    }
}
