omitted_paths:
  - eng/*
  - Scripts/*
  - examples/*
language: swift
root_check_enabled: True
required_readme_sections:
  - "Azure .+ client library for iOS"
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_presence_issues:
  - ['sdk/appconfiguration', '#190']
  - ['sdk/appconfiguration/AzureAppConfiguration', '#190']
  - ['sdk/cognitiveservices', '#190']
  - ['sdk/cognitiveservices/AzureCSComputerVision', '#190']
  - ['sdk/core', '#190']
  - ['sdk/core/AzureCore', '#190']
  - ['sdk/storage', '#190']
  - ['sdk/storage/AzureStorageBlob', '#190']
  - ['sdk/textanalytics', '#190']
  - ['sdk/textanalytics/AzureCSTextAnalytics', '#190']
  - ['examples', '#190']
known_content_issues:
  - ['README.md', '#190']
package_indexing_exclusion_list: