# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/communication/
    - sdk/eng/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/communication/
    - sdk/eng/

resources:
  repositories:
  - repository: SwiftPM-AzureCommunicationCommon
    type: github
    name: Azure/SwiftPM-AzureCommunicationCommon
    endpoint: Azure
  - repository: SwiftPM-AzureCommunicationChat
    type: github
    name: Azure/SwiftPM-AzureCommunicationChat
    endpoint: Azure

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: communication
    Artifacts:
    - name: AzureCommunicationCommon
    - name: AzureCommunicationChat
    - name: AzureCommunicationCalling
      skipSwiftPackageManager: true
    SDLStageRepositoriesToScan:
      - repository: SwiftPM-AzureCommunicationCommon
      - repository: SwiftPM-AzureCommunicationChat
