# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*

extends:
  template: templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: sdk
